### ISSUE TITLE
Repositories to inherit

### ISSUE THREAD

**Issue by ararslan** [JuliaCollections/Roadmap#1]
I'll create a checklist here for the repositories we want to inherit from other organizations. Feel free to check off, add, subtract, etc. as needed.

- [x] JuliaLang/DataStructures.jl (see https://github.com/JuliaLang/DataStructures.jl/issues/261)
- [x] JuliaLang/FunctionalCollections.jl (see https://github.com/JuliaLang/FunctionalCollections.jl/issues/30)
- [x] JuliaLang/Iterators.jl (see https://github.com/JuliaLang/Iterators.jl/issues/96)
- [x] Keno/AbstractTrees.jl
- [x] JuliaLang/SortingAlgorithms.jl

**Comment by kmsquire** [comment]
@keno, are you interested in moving https://github.com/Keno/AbstractTrees.jl here?

**Comment by Keno** [comment]
Yes

**Comment by tkelman** [comment]
SortingAlgorithms doesn't entirely fit but is one of the very few remaining packages under JuliaLang

**Comment by ararslan** [comment]
Meh, SortingAlgorithms is close enough IMO. ¯\\\_(ツ)\_/¯

**Comment by kmsquire** [comment]
@keno, the org name has settled, so you should be able to transfer AbstractTrees.jl any time.

**Comment by oxinabox** [comment]
Would JuliaCollections like to own my new package for checking Iterators have been implemented according to the contract?
https://github.com/oxinabox/InterfaceTesting.jl

It is a simple package, but Iterator traits are so easy to mess up.

**Comment by ararslan** [comment]
@oxinabox Looks neat. For now though it would probably make more sense for it to stay in your account as you're likely to continue to be the primary maintainer.

**Comment by timholy** [comment]
Bump @Keno re AbstractTrees. I just added https://github.com/JuliaCollections/LeftChildRightSiblingTrees.jl. It would make sense to give it an AbstractTrees interface, but not, I think, until it's clear that package is going to be maintainable.

**Comment by Keno** [comment]
I'll transfer it.

**Comment by oxinabox** [comment]
I think this is done?
